package imag.quizz.client.game;

import imag.quizz.client.network.ConnectionManager;
import imag.quizz.client.ui.Window;
import imag.quizz.common.Config;
import imag.quizz.common.Controller;
import imag.quizz.common.network.MessageHandler;
import imag.quizz.common.network.SocketHandler;
import imag.quizz.common.protocol.PingPongTask;
import imag.quizz.common.protocol.Separator;
import imag.quizz.common.protocol.message.*;
import imag.quizz.common.tool.Log;

/**
 * Created by Ribesg.
 */
public class ClientController extends MessageHandler implements Controller {

    private       Window            window;
    private final ConnectionManager connectionManager;
    private final PingPongTask      pingPongTask;
    private       long              playerId;
    private       long              currentGame;

    public ClientController(final Config config) {
        super("Controller");
        this.window = null;
        this.connectionManager = new ConnectionManager(config, this);
        this.playerId = -1; // -1 is invalid : no ID yet
        this.currentGame = -1; // -1 is invalid : not yet playing
        this.pingPongTask = new PingPongTask(this, 5_000);
        this.pingPongTask.start();
    }

    public void setWindow(final Window window) {
        this.window = window;
    }

    public void answerSelected(final String textClicked) {
        Log.info("Réponse sélectionnée : \"" + textClicked + '"');
        this.window.lockButtons();
    }

    @Override
    public void handleMessage(final SocketHandler socketHandler, final Message message) {

        switch (message.getCommand()) {
            // all valid messages
            case PING:
                this.connectionManager.send(new PongMessage(this.playerId, message));
                break;
            case PONG:
                this.pingPongTask.pong(socketHandler.getSocket().getLocalPort());
                break;
            case GAMES:
                this.updateAvailableGames((GamesMessage) message);
                break;
            case THEMES:
                this.showAvailableThemes((ThemesMessage) message);
                break;
            case QUESTION:
                this.showQuestion((QuestionMessage) message);
                break;
            case NOANSWER:
                this.questionTimeout((NoAnswerMessage) message);
                break;
            case WAIT:
                this.waitForOpponent((WaitMessage) message);
                break;
            case END:
                this.gameEnded((EndMessage) message);
                break;

            // ack messages
            case OK:
                switch (((OkMessage) message).getSource().getCommand()) {
                    case REGISTER:
                        this.connectionManager.send(new GamesMessage(this.playerId, null));
                    case LOGIN:
                        this.setPlayerId(message.getSenderId());
                        this.window.loggedIn();
                        break;
                }
                break;
            case NOK:
                this.handleNok((NokMessage)message);
                // wut
                break;

            // invalid messages
            case INIT:
            case REGISTER:
            case LOGIN:
            case PLAY:
            case DROP:
            case NEW:
            case THEME:
            case GAME:
            case ANSWER:
                //TODO: wtf : messages for servers
            default:
                // TODO KEK
                this.connectionManager.send(new NokMessage(playerId, "Unhandled message", message));
        }
    }

    private void handleNok(NokMessage message) {
        this.window.showError(message.getText());
    }

    private void waitForOpponent(final WaitMessage message) {
        //TODO: autogenerated stub
    }

    private void questionTimeout(final NoAnswerMessage message) {
        this.window.questionTimeout();
        //TODO : ask for next question
    }

    private void showQuestion(final QuestionMessage message) {
        this.window.setPanel(Window.PanelType.CHOICE);
        this.window.setQuestion(message.getQuestion());
        int i = 1;
        for (String answer : message.getAnswers()) {
            this.window.setAnswer(i++, answer);
        }
        this.window.unlockButtons();
    }

    private void showAvailableThemes(final ThemesMessage message) {
        window.setPanel(Window.PanelType.CHOICE);
        window.setQuestion("Choisissez un thème");
        int i = 1;
        for (String theme : message.getThemes()) {
            window.setAnswer(i++, theme);
        }
        window.unlockButtons();
    }

    public void newGame(final String opponent) {
        this.connectionManager.send(new NewMessage(playerId, opponent));
    }

    private void updateAvailableGames(final GamesMessage message) {
        final String data = message.getGamesData();
        this.window.clearGames();
        for (String game : data.split(Separator.LEVEL_1)) {
            if (!game.isEmpty()) {
                final String[] split = game.split(Separator.LEVEL_2);

                final long gameId = Long.parseLong(split[0]);
                final String opponent = split[1];
                final boolean wait = Boolean.parseBoolean(split[2]);
                final int myScore = Integer.parseInt(split[3]);
                final int myCurrentQuestion = Integer.parseInt(split[4]);
                final int oppScore = Integer.parseInt(split[5]);
                final int oppCurrentQuestion = Integer.parseInt(split[6]);

                this.window.addGame(gameId, wait, myScore, myCurrentQuestion, opponent, oppScore, oppCurrentQuestion);
            }
        }
        if (!this.isPlaying()) {
            this.window.setPanel(Window.PanelType.GAMES);
        }
    }

    private void gameEnded(final EndMessage message) {
        //TODO: autogenerated stub
    }

    @Override
    public void lostConnection(final SocketHandler socketHandler) {
        this.pingPongTask.removePort(this.connectionManager.getSocketHandler().getSocket().getLocalPort());
        this.connectionManager.lostConnection();
        this.connect();
    }

    @Override
    public void pingTimeout(final int port) {
        if (this.isLoggedIn()) {
            this.lostConnection(null);
        }
    }

    @Override
    public void ping(final int port) {
        if (this.isLoggedIn()) {
            this.connectionManager.send(new PingMessage(this.playerId));
        }
    }

    public void connect() {
        try {
            this.connectionManager.tryConnect();
            this.pingPongTask.addPort(this.connectionManager.getSocketHandler().getSocket().getLocalPort());
            this.window.connected();
        } catch (final ConnectionManager.NoServerException e) {
            this.window.noConnection();
        }
    }

    public void login(final String username, final char[] password) {
        this.connectionManager.send(new LoginMessage(this.playerId, username,new String(password)));
    }

    public void register(final String username, final char[] password) {
        this.connectionManager.send(new RegisterMessage(this.playerId, username, new String(password)));
    }

    public boolean isLoggedIn() {
        return this.playerId != -1;
    }

    public boolean isPlaying() {
        return this.currentGame != -1;
    }

    private void setPlayerId(long playerId) {
        this.playerId = playerId;
    }
}
