package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class GamesMessage extends Message {

    private final String gamesData;

    public GamesMessage(final long senderId, final String gamesData) {
        super(Command.GAMES, senderId);
    }
    /* package */ GamesMessage(final String[] messageSplit) {
        super(Command.GAMES, Integer.parseInt(messageSplit[1]));
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
