package imag.quizz.common.protocol.message;

public class GamesMessage extends Message {
    private
    public GamesMessage(String[] messageSplit) {
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
