package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class InitMessage extends Message {

    private final String data;

    public InitMessage(final int senderId) {
        super(Command.INIT);
        data = ""; //TODO
    }

    /* package*/ InitMessage(final String[] messageSplit) {
        super(Command.INIT);
        data = messageSplit[2];
        //TODO
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
