package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class InitMessage extends Message {
    public InitMessage() {
        super(Command.INIT);
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
