package imag.quizz.common.protocol.message;

public class NoAnswerMessage extends Message {
    public NoAnswerMessage(String[] messageSplit) {
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
