package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class QuestionMessage extends Message {
    public QuestionMessage(String[] messageSplit) {
        super(Command.QUESTION, Long.parseLong(messageSplit[1]));
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
