package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class ThemesMessage extends Message {
    public ThemesMessage(String[] messageSplit) {
        super(Command.THEMES, Long.parseLong(messageSplit[1]));
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
