package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class ThemeMessage extends Message {
    public ThemeMessage(String[] messageSplit) {
        super(Command.THEME, Long.parseLong(messageSplit[1]));
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
