package imag.quizz.common.protocol.message;

public class ThemeMessage extends Message {
    public ThemeMessage(String[] messageSplit) {
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
