package imag.quizz.common.protocol.message;

import imag.quizz.common.protocol.Command;

public class WaitMessage extends Message {
    public WaitMessage(String[] messageSplit) {
        super(Command.WAIT, Long.parseLong(messageSplit[1]));
        //TODO: autogenerated stub
    }

    @Override
    protected String getParametersString() {
        return null;  //TODO: autogenerated stub
    }
}
